# Generated by Django 3.0.4 on 2020-04-05 12:13

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_auto_20200325_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='detail',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
